# encoding: utf-8
name             'octohost'
maintainer       'Darron Froese'
maintainer_email 'darron@froese.org'
license          'Apache 2.0'
description      'Installs/configures octohost'
version          '0.3.0'
recipe           'octohost::default', 'Installs/configures octohost'

depends 'apt'
depends 'ubuntu_base', '0.6.0'
depends 'octobase', '0.5.0'
depends 'docker', '0.2.0'
depends 'redis'
depends 'nodejs'
depends 'hipache'
depends 'serf'
depends 'gitreceive'
